config/routes.rb
Rails.application.routes.draw do
  get 'exams/new'
  root to: 'enrollments#index'
  resources :enrollments
  resources :students
  resources :attendances
  resources :teachers
  resources :exams
  resources :subjects
  resources :school_years
  resources :marks
  get '/fillmarks', to: 'fillmarks#new'
  get '/results', to: 'fillmarks#display_results', as: 'results'
  put '/results_with_no_marks/',to: 'fillmarks#results_with_no_marks'
  get '/results_with_no_marks/',to: 'fillmarks#results_with_no_marks'
  post '/fillmarks', to: 'fillmarks#create'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :student
  belongs_to :subject
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  has_many :school_years, dependent: :destroy 
  has_many :students, through: :school_years, dependent: :destroy
  has_many :exams
  has_many :subjects
end

app/models/exam.rb
class Exam < ApplicationRecord
  belongs_to :subject
  belongs_to :enrollment
  has_many :marks
end

app/models/mark.rb
class Mark < ApplicationRecord
  belongs_to :student
  belongs_to :exam
  def self.student_exam_mark
    @all_students = Student.all
    @all_students.each do |student|
      counter =  student.attendances.count
      i=0
      while i < counter
        j=0
        while j< 3
          all_ids =  student.attendances[j].subject.exams.ids
          m=0
          while m< all_ids.size
            Mark.create(student_id:student.id,exam_id: all_ids[m])
            m+=1
          end
          j+=1
        end
        i+=1
      end
    end
  end
end

app/models/school_year.rb
class SchoolYear < ApplicationRecord
  belongs_to :enrollment
  belongs_to :student
end

app/models/student.rb
class Student < ApplicationRecord
  has_many :school_years, dependent: :destroy
  has_many :enrollments, through: :school_years, dependent: :destroy
  has_many :subjects
  has_many :attendances, dependent: :destroy
  has_many :subjects, through: :attendances
  has_many :enrollments
  has_many :marks
  def name_with_initial
    "#{firstName} #{lastName}"
  end

end

app/models/subject.rb
class Subject < ApplicationRecord
  belongs_to :teacher, optional: true
  has_many :attendances, dependent: :destroy
  has_many :students, through: :attendances, dependent: :destroy
  has_many :exams
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  has_many :subjects, dependent: :destroy
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :set_enrollment, only: %i[ show edit update destroy ]

  # GET /enrollments or /enrollments.json
  def index
    @enrollments = Enrollment.all
    @students = Student.all
    @enrolledstudent ={}
    @students.each do |std|
      if(std.marks.where(exam_id: 1).first !=nil)
    @enrolledstudent [std.firstName+ " "+std.lastName]= std.marks.where(exam_id: 2).first
      end
  end
   
  end

  # GET /enrollments/1 or /enrollments/1.json
  def show
  end

  # GET /enrollments/new
  def new
    @enrollment = Enrollment.new
  end

  # GET /enrollments/1/edit
  def edit
  end

  # POST /enrollments or /enrollments.json
  def create
    @enrollment = Enrollment.new(enrollment_params)

    respond_to do |format|
      if @enrollment.save
        format.html { redirect_to @enrollment, notice: "Enrollment was successfully created." }
        format.json { render :show, status: :created, location: @enrollment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enrollments/1 or /enrollments/1.json
  def update
    respond_to do |format|
      if @enrollment.update(enrollment_params)
        format.html { redirect_to @enrollment, notice: "Enrollment was successfully updated." }
        format.json { render :show, status: :ok, location: @enrollment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enrollments/1 or /enrollments/1.json
  def destroy
    @enrollment.destroy
    respond_to do |format|
      format.html { redirect_to enrollments_url, notice: "Enrollment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enrollment
      @enrollment = Enrollment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def enrollment_params
      params.require(:enrollment).permit(:className)
    end
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  def new
    @exam = Exam.new
  end
  def create
    @exams = Exam.new(exam_params)
    if @exams.save
      flash[:notice] = 'Exam year successfuly added'
      redirect_to new_exam_path
    else
      flash.now[:alert] = "#{@exams.errors.full_messages} prevented this form from saving"
      render 'new'
    end
  end
  def exam_params
  params.require(:exam).permit(:enrollment_id,:subject_id,:name)
  end
end

app/controllers/marks_controller.rb
class MarksController < ApplicationController
  def edit
     
  end
  def update 
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def new
    @student = Student.new
  end
  def create
    @student = Student.new(students_params)
    if @student.save 
      flash[:notice] = 'student added successfuly'
      redirect_to student_path(@student.id)
    
    else
      flash.now[:alert] = "#{@student.errors.full_messages} prevented this form from saving"
      render 'new'
    end
  end
  def show
      @school_year = SchoolYear.new
      @attendance =Attendance.new
      @subject = Subject.all.count
      @student = Student.find(params[:id])
  end
  private 
  def students_params
    params.require(:student).permit(:firstName,:lastName, :dob)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/fillmarks_helper.rb
module FillmarksHelper
end

app/helpers/marks_helper.rb
module MarksHelper
end

app/helpers/school_years_helper.rb
module SchoolYearsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/enrollments/_form.html.erb
<%= form_with(model: enrollment) do |form| %>
  <% if enrollment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(enrollment.errors.count, "error") %> prohibited this enrollment from being saved:</h2>

      <ul>
        <% enrollment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :className %>
    <%= form.text_field :className %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/enrollments/edit.html.erb
<h1>Editing Enrollment</h1>

<%= render 'form', enrollment: @enrollment %>

<%= link_to 'Show', @enrollment %> |
<%= link_to 'Back', enrollments_path %>

app/views/enrollments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Enrollments</h1>

<table>
  <thead>
    <tr>
      <th>Classname</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @enrollments.each do |enrollment| %>
      <tr>
        <td><%= enrollment.className %></td>
        <td><%= link_to 'Show', enrollment %></td>
        <td><%= link_to 'Edit', edit_enrollment_path(enrollment) %></td>
        <td><%= link_to 'Destroy', enrollment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div><% @enrolledstudent.each do |std| %>
  <div>
 <p> <%= std[0] %></p>
 <p>grade <%= std[1].grade %> </p>
</div>
  <%end%>
</div>

<%= link_to 'New Enrollment', new_enrollment_path %>

app/views/enrollments/new.html.erb
<h1>New Enrollment</h1>

<%= render 'form', enrollment: @enrollment %>

<%= link_to 'Back', enrollments_path %>

app/views/enrollments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Classname:</strong>
  <%= @enrollment.className %>
</p>

<%= link_to 'Edit', edit_enrollment_path(@enrollment) %> |
<%= link_to 'Back', enrollments_path %>